services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: papikos-rentals:latest
    ports:
      - '8080:8080'
    networks:
      - papikos-network
    environment:
      # Gunakan host dari Neon
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    depends_on: [] # <-- Add this to ensure dependencies start first

networks:
  papikos-network:
    driver: bridge
